### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Culvanen** [jaboatman/SecretDoors#2]
[Server thread/ERROR]: Could not load 'plugins/SecretDoors.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/snnappie/secretdoors/SecretDoors : Unsupported major.minor version 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.UnsupportedClassVersionError: com/github/snnappie/secretdoors/SecretDoors : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_80]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_80]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_80]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_80]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_80]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_80]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_80]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
    at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_80]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.7.jar:git-Spigot-f94fe8f-d27e6d0]
    ... 6 more

**Comment by jaboatman** [comment]
"This plugin requires Java 8"
